levex/EnergyNet

- parity/parity-energy.service
Signed-off-by: Levente Kurusa <levex@linux.com>
> parity: create a systemctl unit

- simulation/meter.py
- simulation/tests/test_meter.py
when `GET /tick` is called by the simulation master, the following will happen:
- generate a random energy production (or consumption)
- if negative (consumption), `/transaction/consume` is called on the Smart Meter
- if positive (production), `/transaction/buy` is called on the Smart Meter with price 1
> Simulation client updated with new smart meter API

- client/meter/blockchain.js
> blockchain: replace throw with rejection, fix infinite loop

- simulation/meter.py
- simulation/simulate.py
- simulation/tests/test_meter.py
Some simple metrics are collected by the simulation clients.
The simulation master then, at the end of the simulation, collects these metrics and prints them out.
These are really basic metrics, please suggest more.
> simulation: Collecting and printing metrics

- simulation/bank.py
- simulation/rpc/parity_rpc_client.py
> bank: add python server to give money to simulated accounts

- deploy-vm.sh
- deploy.sh
- kill.sh
- parity/res/config.toml
> Deploy to vm

- simulation/bank.py
no more empty responses
this PR should be fast-tracked
> bank: Add response code

- client/meter/blockchain.js
Previously the loop was serialised, this is bad.
By using promise.all we get a performance boost from original 9s
processing time to around 5s. This boost is reasonable.
> meter: Use promise.all for parallelise loops

- client/meter/meter-server.service
- simulation/simulation-server.service
Create services so our servers can run as daemon
> deploy: Create Services

- ansible/playbooks/create-meter.yaml
Signed-off-by: Levente Kurusa <levex@linux.com>
> ansible: add a meter creating playbook

- ansible/playbooks/create-meter.yaml
> ansible: clean instance, rebuild contracts and reenable services

- client/meter/app.js
- client/meter/package-lock.json
- client/meter/package.json
> client: Fix JSON responses and enable CORS

- dapp/package.json
- dapp/src/client/scripts/app.jsx
Energy price histogram from @egospodinova cherry-picked from a messy branch
> dapp: added histogram for average price of energy from contracts

- dapp/src/client/scripts/app.jsx
- dapp/src/client/scripts/buyEnergyPanel.jsx
- dapp/src/client/scripts/contractsViewPanel.jsx
Modify frontend to use smart meter API so we don't have to use bonds to retrieve contract data.
> Frontend use cached data

- simulation/simulate.py
Fixes wishy washy simulation server
Actually try to run and it ran.
https://bulbapedia.bulbagarden.net/wiki/Wishiwashi_(Pok%C3%A9mon)
> Simulation-server fixes

- simulation/bank.py
Banks spend a lot of money on compliance. Our bank should be compliant
to PEP8 as well.
> bank: make bank PEP8 compliant

- ansible/grafana.ini
- ansible/grafana/dashboards/dashboard.json
- ansible/grafana/datasource.json
- ansible/grafana/grafana.ini
- ansible/playbooks/create-meter.yaml
- client/meter/blockchain.js
- client/meter/routes/transaction.js
- dapp/src/client/scripts/app.jsx
As in labs, this should be working!
> Replace placeholder graphs with nice graphs from Grafana

- simulation/meter.py
- simulation/tests/test_meter.py
Usage:
`-P [price]` sets the selling price in the individual simulation
> simulation-meter: Price is a parameter of the simulation

- client/meter/blockchain.js
> meter: Fix consume/autoBuy

- client/meter/blockchain.js
- client/meter/routes/transaction.js
This enables tracking of flow of energy during simulation
> meter: Enable logging of blockchain transactions

- dapp/src/client/scripts/app.jsx
> Polish gui

- simulation/simulate.py
Add a delay between ticks to all machines to allow operations to end
> simulation: delay between iterations

- dapp/src/client/scripts/availableContractsTable.jsx
> dapp: Fix filtering of available contracts

- .gitignore
- report/Makefile
- report/chapters/introduction.tex
- report/report.tex
Signed-off-by: Levente Kurusa <lkurusa@acm.org>
> report: add a barebones report

- .circleci/config.yml
Signed-off-by: Levente Kurusa <levex@linux.com>
> circleCI: add Circle for building the report

- kill.sh
adds missing shebang to the `kill.sh` script
> script: added shebang to kill.sh

- dapp/src/components/App.jsx
- dapp/src/components/SettingsSell.jsx
> dapp: More file name case fixes

- client/meter/recorder.js
- client/meter/routes/config.js
- simulation/local.json
- simulation/meter.py
- simulation/rpc/parity_rpc_client.py
- simulation/simulate.py
Currently location to which a meter records the usage data to is hard coded,
this makes it modifiable via an API and simulation controller can modify it.
> Fix location name for simulation

- client/meter/blockchain.js
- client/meter/consume.js
- client/meter/sell.js
Use bignumber
update blockchain
sleep
> client: Fix consume

- client/meter/sell.js
@danzvara was drunk at 6pm dc54e32b
> client: fix setter for price

- client/meter/consume.js
- client/meter/sell.js
> client: log 0 when doing nothing

- ansible/grafana/dashboards/dashboard_sim.json
> grafana: dashboard

- client/meter/blockchain.js
- dapp/src/components/Blockchain.jsx
- dapp/src/components/ContractsViewPanel.jsx
- truffle/contracts/Energy.sol
- truffle/contracts/Master.sol
- truffle/test/TestMaster.sol
> contracts: redeploy master, fix date

- client/meter/sell.js
> client: fix concat issue in sell
